### ISSUE TITLE
Clarify: The composite is in full control of the designspace location of the component

### ISSUE THREAD

**Issue by PeterCon** [BlackFoundryCom/variable-components-spec#5]
I gather "the designspace" in this case is that of the composite, not the global designspace?

**Comment by JeremieHornus** [comment]
Yes indeed, variable components have their own designspace. This designspace can be accessed when a composite instanciate the component along with a set of transformations.

**Comment by justvanrossum** [comment]
This also relates to #1.

**Comment by PeterCon** [comment]
Then I'd spell out, "... in full control of the composite design space location of the component..."

You could introduce acronyms after first use, "component design space (CDS)", and then use CDS everywhere appropriate so there's no ambiguity.

**Comment by justvanrossum** [comment]
This should be better now. Feel free to reopen if it is still ambiguous.
