### ISSUE TITLE
Clarify: The global designspace location can affect the composite glyph...

### ISSUE THREAD

**Issue by PeterCon** [BlackFoundryCom/variable-components-spec#6]
>The global designspace location can affect the composite glyph, but it does not need to affect the designspace location of the base glyph directly.

Is this saying that the global designspace (GDS) location can affect the _composite designspace_ location of components?

The OT 'glyf' chapter doesn't use the term "base glyph". Do you mean the first component in the composite description? (I'm guessing No.) Or is this saying that affects from the GDS location on a component do not affect the underlying glyph outline of the component (i.e., doesn't entail any effects on other uses of that glyph outline as a component)? Or, is this saying that the GDS location can affect the underlying outline of a component and that those effects will be seen in the composite?

In saying "doesn't need", it's not clear to me if you're saying, "In some cases, X might not happen" or rather "To achieve the design goal of the proposal, it is not a requirement that..."

**Comment by justvanrossum** [comment]
Thanks, will think about how this can be phrased better. This also relates to #1.

**Comment by justvanrossum** [comment]
I have extended the sentence to clarify that it's indeed about achieving the design goal.

I hope the "base glyph" definition in the new Terminology section addresses the other concern.
