### ISSUE TITLE
Clarify: The base glyph ID. This specifies which glyph we are referencing.

### ISSUE THREAD

**Issue by PeterCon** [BlackFoundryCom/variable-components-spec#7]
Here and elsewhere you use "base glyph", which is not a term used in the OT 'glyf' chapter when discussing composites. It would help if you clarified. In this particular instance, it's not clear if what is meant is the glyph ID of the composite being assembled or of a component used in the composite.

**Comment by PeterCon** [comment]
I note that the term "base glyph" does occur [in discussion of composites in the gvar table](https://docs.microsoft.com/en-us/typography/opentype/spec/gvar#point-numbers-and-processing-for-composite-glyphs), but in that instance it is being used in the sense used by Unicode or in GPOS (i.e., not a combining mark).

**Comment by JeremieHornus** [comment]
Here, 'base glyph' is the actual glyph that is used as a component by a composite.

I understand this may be misleading as 'base glyph' wording is used with different meaning elsewhere in the OT spec.
How would you name this?

**Comment by justvanrossum** [comment]
Yeah, we've been struggling with the terminology, and this should be improved.

I tend to use the term "base glyph" as follows:

- _Composite_: a glyph that is made of components
- _Component_: a reference to another glyph, as part of a Composite
- _Base glyph_: the glyph referenced by a component

But if that's ambiguous, it should be changed.

**Comment by PeterCon** [comment]
For purposes of this document, using "base glyph" would be fine, and I think it's helpful to distinguish between a glyph and reference to the glyph as a component. Just clarify. Perhaps before the Proposal overview section and a short Terminology section?

Another terminology difference is that the OT spec generally uses "variation space" where you have "designspace", though it treats "variation space" as a short form for "design-variation space' (see [Terminology](https://docs.microsoft.com/en-us/typography/opentype/spec/otvaroverview#terminology). But I don't think there's any ambiguity about what is meant, so that is fine. But if you did add a terminology section, you could point out that relationship.

**Comment by justvanrossum** [comment]
Thanks! I think we can switch to "variation space". A terminology section is a good suggestion.
